from flask import Blueprint, request, jsonify, current_app
from app.utils.gmail_service import send_welcome_email, send_password_reset_email, send_order_confirmation
from app.utils.validation import validate_email
import traceback
import os

notifications_bp = Blueprint('notifications', __name__)

@notifications_bp.route('/welcome-email', methods=['POST'])
def send_welcome():
    print("\n=== Welcome Email Request ===")
    data = request.get_json()
    print(f"Request data: {data}")
    
    if not data or not data.get('email') or not data.get('name'):
        print("Error: Missing email or name")
        return jsonify({"message": "Email and name are required"}), 400
    
    email = data['email']
    name = data['name']
    
    # Validate email
    if not validate_email(email):
        print(f"Error: Invalid email format: {email}")
        return jsonify({"message": "Invalid email format"}), 400
    
    try:
        print(f"Sending welcome email to {email}")
        send_welcome_email(email, name)
        print("Welcome email sent successfully")
        return jsonify({"message": "Welcome email sent successfully"}), 200
    except Exception as e:
        print(f"Error sending welcome email: {str(e)}")
        print(traceback.format_exc())
        current_app.logger.error(f"Error sending welcome email: {str(e)}")
        return jsonify({"message": "Failed to send welcome email"}), 500

@notifications_bp.route('/password-reset', methods=['POST'])
def send_reset():
    print("\n=== Password Reset Email Request ===")
    try:
        data = request.get_json()
        print(f"Request data: {data}")
        
        if not data or not data.get('email'):
            print("Error: Missing email")
            return jsonify({"message": "Email is required"}), 400
        
        email = data['email']
        name = data.get('name', None)  # Name is optional
        
        # Validate email
        if not validate_email(email):
            print(f"Error: Invalid email format: {email}")
            return jsonify({"message": "Invalid email format"}), 400
        
        try:
            print(f"Sending password reset email to {email}")
            verification_code = data.get('verification_code')
            if verification_code:
                print(f"Using provided verification code: {verification_code}")
            
            # For local development, simply log the email sending attempt
            if os.environ.get('FLASK_ENV') == 'development':
                print("\n=== DEVELOPMENT MODE: Password Reset Email ===")
                print(f"To: {email}")
                print(f"Verification Code: {verification_code or 'Generated by system'}")
                print("=== End Development Mode Email ===\n")
                return jsonify({"message": "Password reset email sent successfully (development mode)"}), 200
            
            # For production, try to send the actual email
            send_password_reset_email(email, name)
            print("Password reset email sent successfully")
            return jsonify({"message": "Password reset email sent successfully"}), 200
        except Exception as e:
            print(f"Error sending password reset email: {str(e)}")
            print(traceback.format_exc())
            current_app.logger.error(f"Error sending password reset email: {str(e)}")
            return jsonify({"message": "Failed to send password reset email", "error": str(e)}), 500
    except Exception as e:
        print(f"Global error in password reset endpoint: {str(e)}")
        print(traceback.format_exc())
        current_app.logger.error(f"Global error in password reset endpoint: {str(e)}")
        return jsonify({"message": "Internal server error", "error": str(e)}), 500

@notifications_bp.route('/order-confirmation', methods=['POST'])
def send_order_conf():
    print("\n=== Order Confirmation Email Request ===")
    try:
        data = request.get_json()
        print(f"Request data: {data}")
        
        if not data or not data.get('email') or not data.get('order_details'):
            print("Error: Missing email or order details")
            return jsonify({"message": "Email and order details are required"}), 400
        
        email = data['email']
        order_details = data['order_details']
        
        # Validate email
        if not validate_email(email):
            print(f"Error: Invalid email format: {email}")
            return jsonify({"message": "Invalid email format"}), 400
        
        # Validate order_details
        required_fields = ['customer_name', 'order_id', 'total', 'items']
        for field in required_fields:
            if field not in order_details:
                print(f"Error: Missing required field in order details: {field}")
                return jsonify({"message": f"Missing required field in order details: {field}"}), 400
        
        try:
            print(f"Sending order confirmation email to {email}")
            
            # For local development, simply log the email sending attempt
            if os.environ.get('FLASK_ENV') == 'development':
                print("\n=== DEVELOPMENT MODE: Order Confirmation Email ===")
                print(f"To: {email}")
                print(f"Order ID: {order_details['order_id']}")
                print(f"Total: ${order_details['total']}")
                print("=== End Development Mode Email ===\n")
                return jsonify({"message": "Order confirmation email sent successfully (development mode)"}), 200
            
            # For production, send the actual email
            send_order_confirmation(email, order_details)
            print("Order confirmation email sent successfully")
            return jsonify({"message": "Order confirmation email sent successfully"}), 200
        except Exception as e:
            print(f"Error sending order confirmation email: {str(e)}")
            print(traceback.format_exc())
            current_app.logger.error(f"Error sending order confirmation email: {str(e)}")
            return jsonify({"message": "Failed to send order confirmation email", "error": str(e)}), 500
    except Exception as e:
        print(f"Global error in order confirmation endpoint: {str(e)}")
        print(traceback.format_exc())
        current_app.logger.error(f"Global error in order confirmation endpoint: {str(e)}")
        return jsonify({"message": "Internal server error", "error": str(e)}), 500

@notifications_bp.route('/health-check', methods=['GET'])
def health_check():
    """Simple health check endpoint to verify API connectivity"""
    return jsonify({"status": "ok", "message": "API is up and running"}), 200

@notifications_bp.route('/', methods=['GET'])
def root_health_check():
    """Root endpoint for easy access and testing"""
    return jsonify({
        "status": "ok", 
        "message": "Winal Drug Shop API is running", 
        "endpoints": {
            "welcome-email": "POST /api/notifications/welcome-email",
            "password-reset": "POST /api/notifications/password-reset",
            "order-confirmation": "POST /api/notifications/order-confirmation",
            "health-check": "GET /api/notifications/health-check"
        }
    }), 200 